CREATE TABLE aluno (
    id VARCHAR(100) UNIQUE PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    matricula VARCHAR(20) NOT NULL,
    curso VARCHAR(100) NOT NULL,
    idade INT NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    ativo BOOLEAN DEFAULT TRUE
);