CREATE TABLE aluno (
    id VARCHAR(100) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    matricula VARCHAR(20) UNIQUE NOT NULL,
    curso VARCHAR(100) NOT NULL,
    idade INT NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    telefone VARCHAR(15) UNIQUE NOT NULL,
    ativo BOOLEAN DEFAULT TRUE
);